### ISSUE TITLE
app內嵌瀏覽器，AccountKit表單Error Page或驗證成功沒有關閉

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#120]
驗證後完成Form未關閉

![9241060765585](https://user-images.githubusercontent.com/28494579/51723486-423c2f80-2094-11e9-927b-03a494c92d9f.jpg)

**Comment by travishen** [comment]
line的inapp有querystring可以另開瀏覽器: `openExternalBrowser=1`，目前想到的作法是在js判斷是否為line的in app browser，然後js再redirect到加上此querystring的網址，但其他inapp就不能通用這個方法

參考：
https://github.com/f2etw/detect-inapp/blob/master/src/inapp.js

**Comment by mattlin4567** [comment]
已新增 inapp detect，尚未驗證
3380cafc420d0e1c10e1609fa17888c86356f53c

**Comment by mattlin4567** [comment]
f99d2b045ffe83adcd8fb6271673bfbc12daf545

**Comment by travishen** [comment]
iOS的facebook inapp開啟首頁異常緩慢：
* iOS: 5min to open
* Andriod: 10 sec to open

**Comment by travishen** [comment]
#165 
* iOS開啟異常為Redirect loop造成，redirect帶openExternalBrowser參數改為inapp=line才觸發
* Accountkit的參數display改設為modal，在同頁面開啟modal而不另開視窗(popup)
