### ISSUE TITLE
Frontend optimization on mobile 

### ISSUE THREAD

**Issue by mattlin4567** [FroggyTaipei/froggy-service#121]
### 網頁手機版優化

已知問題：

- viewport 在手機鍵盤消失後需重新計算

- 使用其他 APP 內嵌之瀏覽器檢視網頁，AccountKit 驗證視窗不會關閉 #120

**Comment by travishen** [comment]
案件列表換頁時都會focus在搜尋欄
導致鍵盤一直跳出來
使用者根本不想搜索 只想換頁而已

**Comment by travishen** [comment]
先關閉，之後有需要修改另開issue
