### ISSUE TITLE
JWT過期的表單處理方式

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#138]
JWT若超出設定時間未送出表單，預期會出現錯誤，前端接到此錯誤應該重新開啟Accountkit驗證取得新的token

## 行為

JWT過期回傳401 Unauthorized
```
{detail: "Signature has expired."}
```

## 測試方式

1. 於`backend/config/settings.py`修改JWT設定：
```
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=1),
}
```
手動於前端取得jwt token並發出額外請求

2. 或使用自動取得的過期token來測試，透過修改`backend/apps/users/tests/initial.py`：
```
        payload = {
            'id': user.pk,
            'exp': datetime(year=2000, month=1, day=1),
        }
```
根據`.env.example`提供的secret key，此token會固定長這個樣子：
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjo5NDY2ODQ4MDB9.EqjWAWGppFadNNn4EUI8pTY0fBB9NvqSptp68wAjEVc
```

**Comment by mattlin4567** [comment]
新增過期提示 3380cafc420d0e1c10e1609fa17888c86356f53c
