### ISSUE TITLE
Accountkit初始錯誤

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#146]
CI最好加上一段檢查

![image](https://user-images.githubusercontent.com/28494579/52784845-6090bc00-3091-11e9-9e76-7665f2b7d754.png)

**Comment by mattlin4567** [comment]
release ?
雖然只要改一下型別
但是 Doc 上面寫的是 string 而且 dev 環境下執行沒問題

**Comment by travishen** [comment]
@mattlin4567 
前端是靜態的webpack，因此在build image時一定要提供以下參數：
```
# Sentry
VUE_APP_SENTRY_PUBLIC_DSN=

# Google Analytics
VUE_APP_GOOGLE_ANALYTICS=

# AccountKit
VUE_APP_ACCOUNTKIT_VERSION=
VUE_APP_ACCOUNTKIT_APP_SECRET=
VUE_APP_ACCOUNTKIT_APP_ID=
```
#142 把`.env.travis`加密後傳到Travis CI做正式環境測試使用，沒考慮到webpack這點，把以上參數都拔掉，所以AccountKit的APP ID變成undefined
