### ISSUE TITLE
Mobile Enhancement Need

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#150]
### 首頁跑馬燈約3秒後才出現
![9356561624743](https://user-images.githubusercontent.com/28494579/52803982-0eb25b00-30be-11e9-8488-73713093e0c5.jpg)
### 這頁的button frame異常變大
![9356558538568](https://user-images.githubusercontent.com/28494579/52803984-0fe38800-30be-11e9-889a-ecc473f30a7c.jpg)
### 警示字體顏色不明顯
![9356554833227](https://user-images.githubusercontent.com/28494579/52803985-107c1e80-30be-11e9-90d6-cdc4f812da1b.jpg)

**Comment by ankycheng** [comment]
problems fixed
