### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#169]
* 我要服務互動頁面跑版
* 版本：IE 11.0.9600

![image](https://user-images.githubusercontent.com/28494579/52996249-f93f8700-3457-11e9-9781-e24afe35a67a.png)

註：
整個網站的IE相容性應具備完整的測試

**Comment by mattlin4567** [comment]
bb643bbaeb352e05cc6c4d391722eaddeaf4b77b

**Comment by travishen** [comment]
先關閉issue，之後有修正另開issue
