### ISSUE TITLE
K8S 上 Database 的資料沒有設定 PersistentVolumes

### ISSUE THREAD

**Issue by a60814billy** [FroggyTaipei/froggy-service#175]
https://github.com/FroggyTaipei/froggy-service/blob/cdf0e308da7f574b0741a7ca20e50961e53a2a0f/k8s-specifications/db-deployment.yaml#L19-L21

用 emptyDir 的話資料只會放在 k8s node 中，如果未來擴展 node，會造成資料遺失，建議這邊改用 PVC 跟 GKE 請求一個固定的 Storage 做為資料庫的 Volume。

ref. 
1. https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes
2. https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by travishen** [comment]
@a60814billy 
感謝！這是示範的設定，我們production是連到Cloud SQL
