### ISSUE TITLE
Alternative way of Contact

### ISSUE THREAD

**Issue by yingpublic** [FroggyTaipei/froggy-service#208]
Hi, I cannot verify my post through my cell phone. Thus, I found two possible email on the website: froggy@froggy.com and servant@65535studio.com. The first one doesn't work and I am not sure if the later one can work as well. Please provide an alternative way to contact. Thanks!

**Comment by travishen** [comment]
Hi @yingpublic, sorry to hear that. Mobile validation on the website is currently support +886 country code only. Please contact us at **servant@65535studio.com**, we'll glad to be of service. Your case information will also be manually added to database by our staff, to make sure it's visible on the website.
Thanks for the feedback!

**Comment by yingpublic** [comment]
Hi @travishen Got you! Thanks! I'll patiently wait for manually update.

**Comment by travishen** [comment]
HI @yingpublic, have you contacted us at the correct e-mail address?
Just to make sure, We haven't received any e-mails yet that related to this issue.

**Comment by yingpublic** [comment]
Hi, @travishen, thanks for checking me in. I sent the email with title "邱議員選民服務 文教科技類" on 2/21 to both froggy@froggy.com and servant@65535studio.com . The first email was returned so I knew it was a wrong email address. The second email didn't return and also I didn't received any feedback tho. Let me know if I need to send again. Thanks!

**Comment by travishen** [comment]
Hi @yingpublic, just confirmed that we do received this e-mail. We'll reply this e-mail and add to our database very soon. Sorry to keep you waiting.

**Comment by yingpublic** [comment]
@travishen No problem! Thanks for confirming for me. I've been contacted.
