### ISSUE TITLE
Case Data Visualization

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#231]
案件資料視覺化的未來相關功能在此討論

**Comment by yingpublic** [comment]
請問除了案件類別視覺化以外，不知道呱吉團隊願不願意把『人力分配』and/or『議員可支配薪資』（含研究費，助理費、為民服務費、出國考察費、出席費等，或是甚至呱吉自掏腰包）做成類似g0v的中央政府總預算專案呢？讓一般民眾知道，呱吉以及其團隊，投入在法案＆選民服務的時間成本分配，謝謝！

**Comment by travishen** [comment]
@yingpublic, 很好的建議！另開一個issue討論這個功能。

**Comment by yingpublic** [comment]
I am surprised to see that this issue has been followed up since then. May I ask where to see the temporary results?
